name: Check Biome Format

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - uses: pnpm/action-setup@v4
        with:
          version: 9.10

      - name: Install dependencies
        run: pnpm install

      - name: Run Biome format check
        run: pnpm format:check